# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: async_sql.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61sync_sql.proto\"\xb1\x01\n\x0e\x41syncSqlMetaPB\x12\x13\n\x0bresult_rows\x18\x01 \x01(\x05\x12\x16\n\x0eprocessed_rows\x18\x02 \x01(\x03\x12\x17\n\x0fprocessed_bytes\x18\x03 \x01(\x03\x12\x15\n\relapsed_milli\x18\x04 \x01(\x03\x12\x0f\n\x07\x63pu_sec\x18\x05 \x01(\x01\x12\x11\n\tcpu_cores\x18\x06 \x01(\x03\x12\x10\n\x08progress\x18\x07 \x01(\t\x12\x0c\n\x04keys\x18\x08 \x03(\t\" \n\rAsyncSqlRowPB\x12\x0f\n\x07\x63olumns\x18\x01 \x03(\t\"\x97\x01\n\x12\x41syncSqlResponsePB\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x02(\t\x12\x1d\n\x04meta\x18\x03 \x01(\x0b\x32\x0f.AsyncSqlMetaPB\x12\x1c\n\x04rows\x18\x04 \x03(\x0b\x32\x0e.AsyncSqlRowPB\x12\x12\n\nerror_code\x18\x05 \x01(\t\x12\x15\n\rerror_message\x18\x06 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'async_sql_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ASYNCSQLMETAPB._serialized_start=20
  _ASYNCSQLMETAPB._serialized_end=197
  _ASYNCSQLROWPB._serialized_start=199
  _ASYNCSQLROWPB._serialized_end=231
  _ASYNCSQLRESPONSEPB._serialized_start=234
  _ASYNCSQLRESPONSEPB._serialized_end=385
# @@protoc_insertion_point(module_scope)
