name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install .

    - name: Show dependencies
      run: |
        python -m pip freeze

    - name: Run build tests
      run: |
        python -m pytest tests/ci/build-test/