

name: Py2-build-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
        image: python:2.7.18-buster

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 

    - name: Install dependencies
      run: |
        python -V
        python -m pip install --upgrade pip setuptools
        python -m pip install .

    - name: Show dependencies
      run: |
        python -m pip freeze

    - name: Run build tests
      run: |
        python -m pip install pytest
        python -m pytest tests/ci/build-test/